_core:
  default_config_hash: PVw1CqINc8mdBO0v-gKzrhG9fd1pyKwx4wIXdks-k3w
disabled: false
field_template: false
ft-default: default
ft-show-colon: false
ft-layout-builder: false
classes:
  region:
    - bg-light
    - col-md-12
    - card
    - card-body
    - 'd-inline-flex '
    - p-2
    - pt-3
    - m-2
    - 'd-flex '
    - justify-content-center
  field: {  }
use_field_names: true
